services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: embrapa_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - VERSION=${VERSION}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    healthcheck:
      test: ["CMD", "python", "-m", "uvicorn", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3